name: Deploy Superfluid FlowScheduler Subgraphs

on:
  workflow_dispatch:
  push:
    branches:
      - "release-v1/*"
    paths:
      - "subgraphs/flow-scheduler/**"
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: subgraphs/flow-scheduler
    strategy: 
      matrix:
        networks: ["avalanche-c", "arbitrum-one", "bsc-mainnet", "eth-mainnet", "eth-goerli", "xdai-mainnet", "optimism-mainnet", "polygon-mainnet", "polygon-mumbai"]
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install
        run: pnpm install
      - name: Generate YAML & Types
        run: pnpm gen
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
      - name: Graph Auth
        run: pnpm exec graph auth --product hosted-service ${{secrets.THE_GRAPH_ACCESS_TOKEN}}
      - name: Graph Deploy
        run: pnpm exec graph deploy --product hosted-service superfluid-finance/${{format('scheduling-v1-{0}', matrix.networks)}} ${{format('./{0}.subgraph.yaml', matrix.networks)}} 